In [14]:
import pandas as pd
df = pd.read_excel("DecodeX_VoltRide_Dataset.xlsx")

In [15]:
df.head()

,Ride_ID,City,Date,Hour,Pickup_Zone,Drop_Zone,Ride_Distance_km,Estimated_Fare,Surge_Multiplier,EV_Battery_%,Driver_Available,Charging_Station_Nearby,Weather,Ride_Status,Cancellation_By
0,1,Hyderabad,2025-01-01,5,8,3,21.59,374.64,2.0,29,Yes,Yes,Heavy Rain,Completed,NaN
1,2,Mumbai,2025-01-01,13,5,4,4.70,353.66,1.0,61,Yes,No,Rain,Completed,NaN
2,3,Delhi,2025-01-01,11,5,5,3.52,329.88,2.0,30,Yes,Yes,Clear,Completed,NaN
3,4,Bengaluru,2025-01-01,22,9,7,21.28,628.14,2.0,17,Yes,Yes,Clear,Cancelled,System
4,5,Hyderabad,2025-01-01,19,5,2,7.00,526.89,1.5,34,Yes,No,Rain,Completed,NaN

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Ride_ID                  2500 non-null   int64
 1   City                     2500 non-null   object
 2   Date                     2500 non-null   datetime64[ns]
 3   Hour                     2500 non-null   int64
 4   Pickup_Zone              2500 non-null   int64
 5   Drop_Zone                2500 non-null   int64
 6   Ride_Distance_km         2500 non-null   float64
 7   Estimated_Fare           2500 non-null   float64
 8   Surge_Multiplier         2500 non-null   float64
 9   EV_Battery_%             2500 non-null   int64
 10  Driver_Available         2500 non-null   object
 11  Charging_Station_Nearby  2500 non-null   object
 12  Weather                  2500 non-null   object
 13  Ride_Status              2500 non-null   object
 14  Cancellation_By          739 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(5), object(6)
memory usage: 293.1+ KB

In [17]:
df.describe(include='all')

,Ride_ID,City,Date,Hour,Pickup_Zone,Drop_Zone,Ride_Distance_km,Estimated_Fare,Surge_Multiplier,EV_Battery_%,Driver_Available,Charging_Station_Nearby,Weather,Ride_Status,Cancellation_By
count,2500.00000,2500,2500,2500.0000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500,2500,2500,2500,739
unique,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,3,2,3
top,NaN,Mumbai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Clear,Completed,Rider
freq,NaN,638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2195,1604,1596,1761,335
mean,1250.50000,NaN,2025-02-21 14:00:57.600000,11.5572,5.466800,5.640400,13.456720,455.819756,1.421600,57.643600,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,2025-01-01 00:00:00,0.0000,1.000000,1.000000,2.010000,120.040000,1.000000,15.000000,NaN,NaN,NaN,NaN,NaN
25%,625.75000,NaN,2025-01-27 00:00:00,6.0000,3.000000,3.000000,7.700000,273.902500,1.000000,36.000000,NaN,NaN,NaN,NaN,NaN
50%,1250.50000,NaN,2025-02-22 00:00:00,12.0000,5.000000,6.000000,13.455000,456.980000,1.200000,58.000000,NaN,NaN,NaN,NaN,NaN
75%,1875.25000,NaN,2025-03-20 00:00:00,17.0000,8.000000,8.000000,19.300000,630.920000,2.000000,79.000000,NaN,NaN,NaN,NaN,NaN
max,2500.00000,NaN,2025-04-15 00:00:00,23.0000,10.000000,10.000000,24.980000,799.680000,2.000000,99.000000,NaN,NaN,NaN,NaN,NaN
std,721.83216,NaN,NaN,6.8581,2.883925,2.855862,6.705038,199.649647,0.382298,24.469591,NaN,NaN,NaN,NaN,NaN

In [18]:
 df.isnull().sum()

Ride_ID                       0
City                          0
Date                          0
Hour                          0
Pickup_Zone                   0
Drop_Zone                     0
Ride_Distance_km              0
Estimated_Fare                0
Surge_Multiplier              0
EV_Battery_%                  0
Driver_Available              0
Charging_Station_Nearby       0
Weather                       0
Ride_Status                   0
Cancellation_By            1761
dtype: int64

In [19]:
df['Cancellation_By'] = df['Cancellation_By'].fillna('None')

In [20]:
df.isnull().sum()

Ride_ID                    0
City                       0
Date                       0
Hour                       0
Pickup_Zone                0
Drop_Zone                  0
Ride_Distance_km           0
Estimated_Fare             0
Surge_Multiplier           0
EV_Battery_%               0
Driver_Available           0
Charging_Station_Nearby    0
Weather                    0
Ride_Status                0
Cancellation_By            0
dtype: int64

In [25]:
df.head()

,Ride_ID,City,Date,Hour,Pickup_Zone,Drop_Zone,Ride_Distance_km,Estimated_Fare,Surge_Multiplier,EV_Battery_%,Driver_Available,Charging_Station_Nearby,Weather,Ride_Status,Cancellation_By,Is_Cancelled,Demand,Peak_Hour,Battery_Level
0,1,Hyderabad,2025-01-01,5,8,3,21.59,374.64,2.0,29,Yes,Yes,Heavy Rain,Completed,None,0,1,Non-Peak,Low
1,2,Mumbai,2025-01-01,13,5,4,4.70,353.66,1.0,61,Yes,No,Rain,Completed,None,0,1,Non-Peak,High
2,3,Delhi,2025-01-01,11,5,5,3.52,329.88,2.0,30,Yes,Yes,Clear,Completed,None,0,1,Non-Peak,Low
3,4,Bengaluru,2025-01-01,22,9,7,21.28,628.14,2.0,17,Yes,Yes,Clear,Cancelled,System,1,1,Non-Peak,Low
4,5,Hyderabad,2025-01-01,19,5,2,7.00,526.89,1.5,34,Yes,No,Rain,Completed,None,0,1,Peak,Medium

In [26]:
df.columns

Index(['Ride_ID', 'City', 'Date', 'Hour', 'Pickup_Zone', 'Drop_Zone',
       'Ride_Distance_km', 'Estimated_Fare', 'Surge_Multiplier',
       'EV_Battery_%', 'Driver_Available', 'Charging_Station_Nearby',
       'Weather', 'Ride_Status', 'Cancellation_By', 'Is_Cancelled', 'Demand',
       'Peak_Hour', 'Battery_Level'],
      dtype='object')

In [27]:
pip install psycopg2.binary sqlalchemy

Requirement already satisfied: psycopg2.binary in c:\users\kiit\onedrive\documents\appl\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\kiit\onedrive\documents\appl\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\kiit\onedrive\documents\appl\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kiit\onedrive\documents\appl\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [28]:
import pandas as pd
from sqlalchemy import create_engine

username = "postgres"
password = "Aahana123"
host = "localhost"
port = "5432"
database = "decode_voltride"   # 👈 your chosen name

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Load Excel
df = pd.read_excel("DecodeX_VoltRide_Dataset.xlsx")

# Upload
df.to_sql("voltride_data", engine, if_exists="replace", index=False)

print("Data uploaded successfully")

Data uploaded successfully

In [31]:
df['Is_Cancelled'] = df['Ride_Status'].apply(lambda x: 1 if x == 'Cancelled' else 0)

In [32]:
df['Demand'] = 1

In [33]:
df['Peak_Hour'] = df['Hour'].apply(
    lambda x: 'Peak' if 7<=x<=10 or 17<=x<=21 else 'Non-Peak'
)

In [34]:
df['Battery_Level'] = pd.cut(
    df['EV_Battery_%'],
    bins=[0,30,60,100],
    labels=['Low','Medium','High']
)

In [35]:
print(df.columns)

Index(['Ride_ID', 'City', 'Date', 'Hour', 'Pickup_Zone', 'Drop_Zone',
       'Ride_Distance_km', 'Estimated_Fare', 'Surge_Multiplier',
       'EV_Battery_%', 'Driver_Available', 'Charging_Station_Nearby',
       'Weather', 'Ride_Status', 'Cancellation_By', 'Is_Cancelled', 'Demand',
       'Peak_Hour', 'Battery_Level'],
      dtype='object')

In [36]:
df.to_sql("voltride_data", engine, if_exists="replace", index=False)

print("UPLOAD DONE")

UPLOAD DONE